AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: rest api with mux router
Resources:
  RecipesAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: .
      Runtime: go1.x
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyHowmRecipesApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/recipes'
    Export:
      Name: MyHowmRecipesApi
